name: Nuclei

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  targeturl: 'https://web.archive.org/cdx/search/cdx?url=*.fujcharity.ae&fl=original&collapse=urlkey'

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nuclei
        run: |
          wget https://github.com/projectdiscovery/nuclei/releases/download/v2.9.8/nuclei_2.9.8_linux_amd64.zip
          unzip nuclei_2.9.8_linux_amd64.zip
          sudo mv nuclei /usr/local/bin/

      - name: Get targets
        run: |
          curl $targeturl -o targets.txt

      - name: Divide targets
        run: |
          split -n l/5 targets.txt targets

      - name: Run Nuclei scan 1
        run: |
          timeout 5h sh -c 'nuclei -l targetsaa -es info | tee -a nuclei-scan-result1.txt'
        shell: bash

      - name: Run Nuclei scan 2
        run: |
          timeout 5h sh -c 'nuclei -l targetsab -es info | tee -a nuclei-scan-result2.txt'
        shell: bash

      - name: Run Nuclei scan 3
        run: |
          timeout 5h sh -c 'nuclei -l targetsac -es info | tee -a nuclei-scan-result3.txt'
        shell: bash

      - name: Run Nuclei scan 4
        run: |
          timeout 5h sh -c 'nuclei -l targetsad -es info | tee -a nuclei-scan-result4.txt'
        shell: bash

      - name: Run Nuclei scan 5
        run: |
          timeout 5h sh -c 'nuclei -l targetsae -es info | tee -a nuclei-scan-result5.txt'
        shell: bash

      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: Saving Result
          path: |
            nuclei-scan-result1.txt
            nuclei-scan-result2.txt
            nuclei-scan-result3.txt
            nuclei-scan-result4.txt
            nuclei-scan-result5.txt
