name: Nuclei

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  targeturl: 'https://web.archive.org/cdx/search/cdx?url=*.fujcharity.ae&fl=original&collapse=urlkey'

jobs:
  recon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url-index: [0, 1, 2, 3, 4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nuclei
        run: |
          wget https://github.com/projectdiscovery/nuclei/releases/download/v2.9.8/nuclei_2.9.8_linux_amd64.zip
          unzip nuclei_2.9.8_linux_amd64.zip
          sudo mv nuclei /usr/local/bin/

      - name: Get targets
        run: |
          curl $targeturl -o targets.txt

      - name: Divide targets
        run: |
          awk '{ total = NR; lines[total] = $0 } END { for (i = 1; i <= total; i++) print lines[i] > "targets" int((i-1)/total*5)+1 ".txt" }' targets.txt

      - name: Run Nuclei scan
        run: |
          nuclei -l targets${{ matrix.url-index + 1 }}.txt -es info | tee -a nuclei-scan-result${{ matrix.url-index + 1 }}.txt
        shell: bash

      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: Saving Result
          path: nuclei-scan-result${{ matrix.url-index + 1 }}.txt
