name: Nuclei

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  targeturl: 'https://web.archive.org/cdx/search/cdx?url=*.fujcharity.ae&fl=original&collapse=urlkey'

jobs:
  recon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nuclei
        run: |
          wget https://github.com/projectdiscovery/nuclei/releases/download/v2.9.8/nuclei_2.9.8_linux_amd64.zip
          unzip nuclei_2.9.8_linux_amd64.zip
          sudo mv nuclei /usr/local/bin/

      - name: Create target URLs file
        run: echo "${{ env.targeturl }}" > targets.txt

      - name: Divide target URLs
        run: |
          total_lines=$(wc -l < targets.txt)
          lines_per_part=$((total_lines / 5))
          start_line=$((lines_per_part * (part - 1) + 1))
          end_line=$((start_line + lines_per_part - 1))
          sed -n "${start_line},${end_line}p" targets.txt > targets_${{ matrix.part }}.txt

      - name: Scanning
        run: |
          timeout 5h sh -c 'nuclei -l targets_${{ matrix.part }}.txt -es info | tee -a nuclei-scan-result_${{ matrix.part }}.txt'
        shell: bash

      - name: Save results
        uses: actions/upload-artifact@v2
        with:
          name: Result Part ${{ matrix.part }}
          path: nuclei-scan-result_${{ matrix.part }}.txt
